### ISSUE TITLE
Just some info request

### ISSUE THREAD

**Issue by Code-Slave** [kensand/rss-lemmy-bot#1]
I set it up and it seems to be running. All i see in the logs is 
Scanning feed https://apnews.com/hub/ap-top-news.rss with latestTime: Tue Jun 27 2023 14:46:15 GMT+0000 (Coordinated Universal Time)

no posts in the community. is there more detailed log?

**Comment by Code-Slave** [comment]
heres my config. running latest lemmy

{
  "lemmy": {
    "login": {
      "username_or_email": "xxxx",
      "password": "xxxx"
    },
    "instanceUrl": "https://lemmy.mayes.io"
  },
  "feeds": [
    {
      "feedUrl": "https://apnews.com/hub/ap-top-news.rss",
      "lemmyCommunities": [
        {
          "communityName": "news_feeds",
          "instanceUrl": "https://lemmy.mayes.io"
        }
      ]
    }
  ]
}

**Comment by kensand** [comment]
Yeah sorry, haven't had a chance to fully document it all.

By default it scans each RSS feed hourly (do you think that's too high? I don't want people to hammer innocent RSS feeds by accident...) You can override that by setting either a new default schedule, or on a per feed basis. The formatting for the schedule configs comes from the [Toad-Scheduler SimpleIntervalSchedule](https://github.com/kibertoad/toad-scheduler/blob/main/lib/engines/simple-interval/SimpleIntervalSchedule.ts), just so you understand how to configure them.

```
{
  "lemmy": {
    "login": {
      "username_or_email": "xxxx",
      "password": "xxxx"
    },
    "instanceUrl": "https://lemmy.mayes.io"
  },
  "defaultSchedule": {
    "minutes": 15
  },
  "feeds": [
    {
      "feedUrl": "https://apnews.com/hub/ap-top-news.rss",
      "lemmyCommunities": [
        {
          "communityName": "news_feeds",
          "instanceUrl": "https://lemmy.mayes.io"
        }
      ],
      "schedule": {
        "minutes": 5
      }
    }
  ]
}
```

The bot also does its best to avoid posting the same item from a feed twice. It does this by recording its startup time and only posting stories that are after it. Any time it posts a item for a given feed, it records the timestamp for that item, and will not post any other items older than that timestamp for that feed. Items will be posted in order of their published dates. All aformentioned timestamps are volatile and will be lost at exit.

You can override the startup timestamp by setting the `START_TIME` environment variable with a timestamp able to be parsed by the JS [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) constructor. This comes in handy for back-filling & testing, as it will post all items more recent than that start time in all configured feeds.

I hope that answers your questions. I'll take some time to add this all to the README tonight, and I'm also going to add some logging this evening just for when the scan on each feed starts/stops - hopefully that makes things a little bit clearer too.

Thanks for taking an interest :) Please feel free to re-open if you have further questions.

**Comment by Code-Slave** [comment]
i just redid instance so ill look again.
