### ISSUE TITLE
Better formatting possible?

### ISSUE THREAD

**Issue by markstos** [kensand/rss-lemmy-bot#14]
Here's an example of a link I just posted and then viewed in Memmy on iOS:

![image](https://github.com/kensand/rss-lemmy-bot/assets/25829/bf1ae335-eec5-4d66-9e5c-3fd506ad9a82)

Here's an example that seems like it should be possible, using a photo found via metadata and a snippet. 

![image](https://github.com/kensand/rss-lemmy-bot/assets/25829/8476872b-fd29-42eb-8265-081fa1e96933)

**Comment by kensand** [comment]
Absolutely - let me have a look at it. :+1: I think it also will depend on individual feeds as well - it depends on which fields they put the information in. For example, one may put the title in both the title and the content fields, while another may actually put the story in the content. I'll try improving it a bit and fixing the markdown though.

**Comment by markstos** [comment]
I look a look at a specific feed to see what was possible:

https://limestonepost.com/feed/

Here's what I noticed:

 * There's no image for the item in the feed, and the RSS spec doesn't include tags for item-specific images anyway. 
 * The <description> includes the entire post (!!). Re-posting entire posts is not my goal here.

We have another resource to use, which is the OpenGraph tags, so I took at look at the open graph tags on the page:

https://limestonepostmagazine.com/why-i-found-myself-running-50-miles

Here, the Open Graph tags were present, and did include an image to use, but the "og:description" tag was left empty.

```
   <meta property="og:type" content="article" />
                        <meta property="og:url" content="http://limestonepostmagazine.com/why-i-found-myself-running-50-miles/"/>
                        <meta property="og:site_name" content="Limestone Post Magazine" />
                       <meta property="og:title" content="Why I Found Myself Running 50 Miles Alone in the Wintertime" />
                      <meta property="og:description" content=""/>
                     <meta property="og:image" content="https://limestonepostmagazine.com/wp-content/uploads/2024/02/feature-3.j
pg" />
```

That's OK. If the OpenGraph image could be used to supplement the RSS data, that would be an improvement. I had assumed that Lemmy might handle that on the server side, as a lot of services seem to pull in OpenGraph metadata when content is shared socially.  Here, we can also take the lack of "og:description" content as a signal that the publisher prefers not to have a description included when shared socially.

**Comment by poVoq** [comment]
It also mangles the formatting a bit it seems. For example see this output:

https://slrpnk.net/post/7696091

Especially those two numbered list items at the bottom.

In the original they are within the text, see here: https://movim.slrpnk.net/node/pubsub.slrpnk.net/solarpunk/long-text-solarpunk-blogging-community-on-the-slrpnk-movim-zSDxO3

**Comment by kensand** [comment]
Formatting should be configurable on a per-feed basis using [mustache](https://github.com/janl/mustache.js) now - see the [updated section in the README](https://github.com/kensand/rss-lemmy-bot?tab=readme-ov-file#configjson).

If you think we should rework the default format, lets start a new issue for that :+1:
