### ISSUE TITLE
Option to only post the link to the feed and not try to replicate it on Lemmy?

### ISSUE THREAD

**Issue by poVoq** [kensand/rss-lemmy-bot#18]
Sometimes the full text in a RSS feed is just mangled up or intentionally broken to avoid scraping. It is also a copyright concern for some feeds to be replicated in full.

So it would be nice to have an option per feed to not try and pull the full text or the RSS provided summary and just share the link to the original.

Thanks!

**Comment by kensand** [comment]
Sure, makes sense 👍 I'll have a look at this alongside #14 - IMO this is in the same vein

**Comment by kensand** [comment]
Whoops, sorry - clicked the wrong button and closed accidentally.

**Comment by kensand** [comment]
Added configurable formatting on a per-feed basis now - see #14 . If you want to disable the body or url altogether, you can provide a `null` value for the format for them:

```json
{
  "lemmy": {
    "login": {
      "username_or_email": "<your lemmy username>",
      "password": "<your lemmy password>"
    },
    "instanceUrl": "<your lemmy home instance url, beginning with 'https://`"
  },
  "feeds": [
    {
      "feedUrl": "https://Some.Fake.Rss.Feed.URL.abcd1234567890/top_news.rss",
      "schedule": {
        "days": 2
      },
      "lemmyCommunities": [
        {
          "communityName": "the_news",
          "instanceUrl": "https://Some.Fake.Lemmy.Instance.URL.abcd1234567890"
        }
      ],
      "nsfw": true,
      "format": {
        "title": "Look at this title!: {{{title}}}",
        "url": "{{#link}}web.archive.org/{{{link}}}{{/link}}",
        "body": null
      }
    }
  ]
}
```

I'm pretty sure that should suffice for this issue, but feel free to re-open if you disagree.
