### ISSUE TITLE
Mark post as NSFW

### ISSUE THREAD

**Issue by Ruriko** [kensand/rss-lemmy-bot#3]
Is it possible for the bot to mark a post as NSFW on lemmy?

**Comment by kensand** [comment]
Sorry for the late response - how would you propose knowing if a post from an RSS feed is NSFW? or are you looking to mark an entire feed as NSFW?

**Comment by markstos** [comment]
This is possible with the latest lemmy-js-client API: 

https://join-lemmy.org/api/interfaces/CreatePost.html

 There's an nsfw boolean.

**Comment by kensand** [comment]
Agreed - I think the _only_ way to do this is to mark an entire RSS feed as NSFW. Will look into implementing.

**Comment by markstos** [comment]
Right. I think there's no safe way in the RSS spec to figure out if a specific post is NSFW.
