### ISSUE TITLE
Details should be logged for failed postings

### ISSUE THREAD

**Issue by markstos** [kensand/rss-lemmy-bot#7]
Today the bot failed to post but the logs jsut say there was an error and the error was "undefined".  Below is an example.

When there's a failure to post to Lemmy, the HTTP status code and full HTTP body response should be logged for the best chance of debugging what went wrong. 

> Mar 03 18:47:13 host rss-lemmy-bot[18636]: Scanning feed https://example.com/feed/. Latest Item in feed is Sun Mar 03 2024 03:17:11 GMT+0000 (Coordinated Universal Time).
> Mar 03 18:47:14 host rss-lemmy-bot[18636]: Posting item Some Title from https://example.com/feed/ published at Sun Mar 03 2024 23:45:22 GMT+0000 (Coordinated Universal Time)
> Mar 03 18:47:15 host rss-lemmy-bot[18636]: Error while handling task https://example.com/feed/: undefined

**Comment by markstos** [comment]
I'm starting to look at this now, by adding a try/catch around the HTTP post call. 

But there should perhaps be a general try/catch for other unexpected exceptions as well.

**Comment by kensand** [comment]
Was this solved by #8 ?

**Comment by markstos** [comment]
Let's say "good enough for now". Diagnostics were improved and thanks to your 0.19.0 compat fixes, I no longer get the login error (so my personal interest in improving this has dropped considerably...)

https://midwest.social/c/bloomington_in

**Comment by kensand** [comment]
Sounds good, glad it's working for you :smile:
